### ISSUE TITLE
Update to patch 10.1?

### ISSUE THREAD

**Issue by DrkWntr** [jimmy58663/Craftility#16]
Any chance of an update to patch 10.1? Several new reagents have been added that are not available through the sim mode. Thanks

**Comment by jimmy58663** [comment]
@DrkWntr sorry my sub expired and due to RL situations I will not be resubbing at this time so I can no longer continue development. 

The code is released and available for someone else to take over if they would like. I am available for questions if someone does want to take it over.

**Comment by Steffen-Bach** [comment]
I have tried to patch together a rudimentary support under https://github.com/jimmy58663/Craftility/pull/17
